import User from '../models/User.js';
import Portfolio from '../models/Portfolio.js';
import generateToken from '../utils/generateToken.js';
const userPayload = (user) => ({ id: user._id, name: user.name, email: user.email, role: user.role, avatar: user.avatar, isActive: user.isActive });
export const register = async (req, res, next) => { try { const { name, email, password } = req.body; if (await User.findOne({ email })) { res.status(409); throw new Error('Email already registered'); } const user = await User.create({ name, email, password }); await Portfolio.create({ user: user._id }); res.status(201).json({ success: true, data: { user: userPayload(user), token: generateToken(user._id) } }); } catch (error) { next(error); } };
export const login = async (req, res, next) => { try { const user = await User.findOne({ email: req.body.email }).select('+password'); if (!user || !(await user.matchPassword(req.body.password))) { res.status(401); throw new Error('Invalid email or password'); } if (!user.isActive) { res.status(403); throw new Error('Account is deactivated'); } res.json({ success: true, data: { user: userPayload(user), token: generateToken(user._id) } }); } catch (error) { next(error); } };
export const getProfile = async (req, res) => res.json({ success: true, data: req.user });
export const updateProfile = async (req, res, next) => { try { const allowed = ['name', 'avatar']; allowed.forEach((field) => { if (req.body[field] !== undefined) req.user[field] = req.body[field]; }); await req.user.save(); res.json({ success: true, data: userPayload(req.user) }); } catch (error) { next(error); } };
export const changePassword = async (req, res, next) => { try { const user = await User.findById(req.user._id).select('+password'); if (!(await user.matchPassword(req.body.currentPassword))) { res.status(400); throw new Error('Current password is incorrect'); } user.password = req.body.newPassword; await user.save(); res.json({ success: true, message: 'Password changed successfully' }); } catch (error) { next(error); } };
