import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import ChartBox from '../components/ChartBox.jsx';
import DataTable from '../components/DataTable.jsx';
import StatCard from '../components/StatCard.jsx';
import Loader from '../components/Loader.jsx';
import { portfolioAPI } from '../services/api.js';
import { money, percent } from '../utils/formatters.js';
export default function Portfolio() { const [portfolio, setPortfolio] = useState(null); const load = async () => setPortfolio((await portfolioAPI.get()).data); useEffect(() => { load(); }, []); const sell = async (stockId) => { const qty = Number(prompt('Quantity to sell', '1')); if (!qty) return; try { await portfolioAPI.sell({ stockId, quantity: qty }); toast.success('Sold successfully'); load(); } catch (err) { toast.error(err.message); } }; if (!portfolio) return <Loader />; const rows = portfolio.holdings; return <div className="page"><h1>Portfolio</h1><div className="stats-grid"><StatCard label="Current Balance" value={money(portfolio.walletBalance)} /><StatCard label="Invested Amount" value={money(portfolio.totalInvestment)} /><StatCard label="Profit / Loss" value={money(portfolio.profitLoss)} tone={portfolio.profitLoss >= 0 ? 'success' : 'danger'} /><StatCard label="ROI" value={percent(portfolio.totalInvestment ? portfolio.profitLoss / portfolio.totalInvestment * 100 : 0)} /></div><div className="grid-2"><section><h4>Asset allocation</h4><ChartBox type="pie" labels={rows.map((h) => h.stock.symbol)} values={rows.map((h) => h.quantity * h.stock.currentPrice)} /></section><section><h4>Portfolio trend</h4><ChartBox type="bar" labels={rows.map((h) => h.stock.symbol)} values={rows.map((h) => (h.stock.currentPrice - h.averagePrice) * h.quantity)} label="Gain/Loss" /></section></div><DataTable rows={rows} columns={[{key:'symbol',label:'Stock',render:(r)=>r.stock.symbol},{key:'quantity',label:'Quantity'},{key:'averagePrice',label:'Average',render:(r)=>money(r.averagePrice)},{key:'currentPrice',label:'Current',render:(r)=>money(r.stock.currentPrice)},{key:'gain',label:'Gain/Loss',render:(r)=>money((r.stock.currentPrice - r.averagePrice) * r.quantity)},{key:'sell',label:'Action',render:(r)=><button className="btn btn-sm btn-danger" onClick={()=>sell(r.stock._id)}>Sell</button>}]} /></div>; }
